[versions]
kotlin = "1.8.10"
resources = "0.2.4"
benchmark = "0.4.7"

[libraries]
resources = { module = "com.goncalossilva:resources", version.ref = "resources" }
kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1"
kotlinx-benchmark = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-runtime", version.ref = "benchmark" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

kotlinx-benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "benchmark" }
publish = { id = "com.vanniktech.maven.publish", version = "0.19.0" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.20.0" }
dokka = { id = "org.jetbrains.dokka", version = "1.7.20" }
resources = { id = "com.goncalossilva.resources", version.ref = "resources" }